name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy-shiny:
    runs-on: ubuntu-20.04
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/xenial/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        id: install-r
        with:
          r-version: release
          http-user-agent: "R/4.0.0 (ubuntu-20.04) R (4.0.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions"

      - name: Install packages and system dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          pak::pkg_install(
            pkg = c(
              "shiny",
              "rsconnect",
              "tidyverse",
              "ellisvalentiner/lubridateExtras",
              "scales",
              "glue",
              "sentryR",
              "shinythemes",
              "conflicted"
            )
          )
          pak::pkg_system_requirements(
            package = c(
              "shiny",
              "rsconnect",
              "tidyverse",
              "scales",
              "glue",
              "sentryR",
              "shinythemes",
              "conflicted"
            ),
            os = "ubuntu",
            os_release = "20.04",
            execute = TRUE,
            echo = TRUE
          )
        shell: Rscript {0}
      
      - name: Create Renviron
        env:
          SENTRY_DSN: ${{ secrets.RSCONNECT }}
        run: |
          echo 'SENTRY_DSN=${SENTRY_DSN}' >> .Renviron
          echo 'ENVIRONMENT=production' >> .Renviron

      - name: Deploy
        env:
          RSCONNECT: ${{ secrets.RSCONNECT }}
        run: |
          rsconnect::setAccountInfo(
            name='ellis-valentiner',
            token='3F668E0B320A9F3CB7B558CB47379486',
            secret=Sys.getenv("RSCONNECT")
          )
          rsconnect::deployApp(appName = 'dte-rate-comparison')
        shell: Rscript {0}
