name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/all/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        id: install-r
        with:
          r-version: release

      - name: Install packages and system dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          pak::pkg_install(
            pkg = c(
              "shiny",
              "rsconnect",
              "tidyverse",
              "ellisvalentiner/lubridateExtras",
              "scales",
              "glue",
              "sentryR",
              "shinythemes",
              "conflicted"
            )
          )
        shell: Rscript {0}
      
      - name: Create Renviron
        env:
          SENTRY_DSN: ${{ secrets.RSCONNECT }}
        run: |
          echo 'SENTRY_DSN=${SENTRY_DSN}' >> .Renviron
          echo 'ENVIRONMENT=production' >> .Renviron

      - name: Deploy
        env:
          RSCONNECT: ${{ secrets.RSCONNECT }}
        run: |
          rsconnect::setAccountInfo(
            name='ellis-valentiner',
            token='3F668E0B320A9F3CB7B558CB47379486',
            secret=Sys.getenv("RSCONNECT")
          )
          rsconnect::deployApp(appName = 'dte-rate-comparison')
        shell: Rscript {0}
